# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iatKlC-9FgKJcapg23TqNQ2at-rnfdWl
"""

#Variables

a = 4       # x is of type int
b = "Sally" # x is now of type str

x = str(3)    # x will be '3'
y = int(3)    # y will be 3
z = float(3)  # z will be 3.0


print(a)
print(b)
print(x)
print(y)
print(z)

#list


my_list = ["apple", "banana", "cherry", "apple", "cherry"]
list2 = [1, 5, 7, 9, 3]
list3 = [True, False, False]
print(my_list)
print(list2)
print(list3)
print(len(my_list))

# find data type
print(type(my_list))
print(type(list2))
print(type(list3))

#append an element
my_list.append("amrood")

list3.clear()
print(list3)
my_list.insert(2,"orange")
print(my_list)


#tuple

my_tuple = ("apple", "banana", "cherry", "apple", "cherry")
my_tuple1 = ("abc", 34, True, 40, "male")
function_tuple = tuple(("Amaar", "Kashif", "Mahmood")) # note the double round-brackets


print(my_tuple)
print(my_tuple1)
print(type(my_tuple1))
print(function_tuple)

print(my_tuple.count("apple"))


#Set

my_set = {"apple", "banana", "cherry", "apple"}
my_set1 = {"apple", "banana", "cherry", True, 1, 2}

my_set.add("Amrood")
print(my_set1)
print(my_set)
print(my_set.difference(my_set1))
print(my_set.intersection(my_set1))
print('my_set U my_set1 = ', my_set.union(my_set1))
my_set.clear()
print(my_set)


#Dict

my_dict = {
  "20sw002": "Rameez",
  "20sw005": "Niaz",
  "20sw003": "Zaid Ahmed",
  "20sw007": "Ali Raza",
  "20sw008": "Ali Mehran",
  "20sw004": "ALi Nyn",
}
print(my_dict["20sw004"])
print(len(my_dict))
for std in my_dict:
    student = my_dict[std]
    print(student)

print(my_dict.clear())


#if else if

a = 200
b = 33
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")
else:
  print("a is greater than b")


#for loop
roll = ["20sw001", "20sw002", "20sw004","20sw006","20sw005","20sw023","20sw025","20sw0027","20sw013","20sw014","20sw015","20sw016","20sw017","20sw018","20sw019","20sw0020"]
for x in roll:

   print(x)

#output


roll = ["20sw001", "20sw002", "20sw004","20sw006","20sw005","20sw023","20sw025","20sw0027","20sw013","20sw014","20sw015","20sw016","20sw017","20sw018","20sw019","20sw0020"]
for x in roll:

         print(x)


#while loop

i = 1
while i < 20:
  print(i)
  if i == 15:
    break
  i += 1